name: example
version: 1.0.0
author: "Sergey Penkovsky <sergey.penkovsky@gmail.com>"
homepage: localhost

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  cherrypick:
    path: ../

dev_dependencies:
  test: ^1.16.8
