name: example
version: 1.0.0
homepage: localhost
publish_to: none

environment:
  sdk: '>=3.2.0 <4.0.0'


dependencies:
  meta: ^1.3.0
  
  cherrypick:
    path: ../

dev_dependencies:
  test: ^1.16.8
